{"uuid":"b9ef5140-6387-4b99-87f4-3a4ea7b1bd30","historyId":"c81adfe6de351c7231470d099ec3ee40","fullName":"ex_Selenium_DataDrivenTesting.DDT_RealTimeScenario.testDataDriven","labels":[{"name":"package","value":"ex_Selenium_DataDrivenTesting.DDT_RealTimeScenario"},{"name":"testClass","value":"ex_Selenium_DataDrivenTesting.DDT_RealTimeScenario"},{"name":"testMethod","value":"testDataDriven"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"ex_Selenium_DataDrivenTesting.DDT_RealTimeScenario"},{"name":"host","value":"DESKTOP-AHMVJTM"},{"name":"thread","value":"39312@DESKTOP-AHMVJTM.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testDataDriven","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file input stream from file: 'E:\\ABTB6x\\LearningSeleniumATB6x\\LearningSeleniumATB6x\\src\\test\\java\\ex_Selenium_DataDrivenTesting\\resources\\TataData.xlsx'","trace":"java.lang.RuntimeException: org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file input stream from file: 'E:\\ABTB6x\\LearningSeleniumATB6x\\LearningSeleniumATB6x\\src\\test\\java\\ex_Selenium_DataDrivenTesting\\resources\\TataData.xlsx'\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:809)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:734)\r\n\tat org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)\r\n\tat org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\nCaused by: org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file input stream from file: 'E:\\ABTB6x\\LearningSeleniumATB6x\\LearningSeleniumATB6x\\src\\test\\java\\ex_Selenium_DataDrivenTesting\\resources\\TataData.xlsx'\r\n\tat org.apache.poi.openxml4j.opc.ZipPackage.openZipEntrySourceStream(ZipPackage.java:212)\r\n\tat org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:199)\r\n\tat org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:171)\r\n\tat org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:247)\r\n\tat org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:179)\r\n\tat org.apache.poi.ooxml.POIXMLDocument.openPackage(POIXMLDocument.java:88)\r\n\tat org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:358)\r\n\tat ex_Selenium_DataDrivenTesting.ExcelReader.getDataFromSheet(ExcelReader.java:139)\r\n\tat ex_Selenium_DataDrivenTesting.DDT_RealTimeScenario.testDataExcel(DDT_RealTimeScenario.java:65)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)\r\n\t... 25 more\r\nCaused by: java.nio.file.NoSuchFileException: E:\\ABTB6x\\LearningSeleniumATB6x\\LearningSeleniumATB6x\\src\\test\\java\\ex_Selenium_DataDrivenTesting\\resources\\TataData.xlsx\r\n\tat java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)\r\n\tat java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)\r\n\tat java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)\r\n\tat java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)\r\n\tat java.base/java.nio.file.Files.newByteChannel(Files.java:379)\r\n\tat java.base/java.nio.file.Files.newByteChannel(Files.java:431)\r\n\tat java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)\r\n\tat java.base/java.nio.file.Files.newInputStream(Files.java:159)\r\n\tat org.apache.poi.openxml4j.opc.ZipPackage.openZipEntrySourceStream(ZipPackage.java:209)\r\n\t... 38 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1739049651346,"stop":1739049651350}